/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mockito;

import java.util.ArrayList;
import java.util.List;

public class Library {
    
	private List<String> livros = new ArrayList<>();
	
	
	public List<String> getLivro(){
		
		return livros;
	}
	
	public void addLivro(String novoLivro){
		livros.add(novoLivro);
	}
}
